import path from "node:path";
import { fileURLToPath } from "node:url";

let databasePromise;
let databaseOverride;

const schema = `
  CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ
  )
`;

async function createPostgresDatabase(connectionString) {
  const { neon } = await import("@neondatabase/serverless");
  const sql = neon(connectionString);
  await sql.query(schema);
  return {
    type: "postgresql",
    async health() { await sql`SELECT 1`; },
    async createContact({ name, email, message }) {
      const rows = await sql`INSERT INTO contacts (name, email, message) VALUES (${name}, ${email}, ${message}) RETURNING id`;
      return Number(rows[0].id);
    },
    async listContacts() {
      return sql`SELECT id, name, email, message, created_at, read_at FROM contacts ORDER BY created_at DESC, id DESC`;
    },
    async markContactRead(id) {
      const rows = await sql`UPDATE contacts SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP) WHERE id = ${id} RETURNING id`;
      return rows.length > 0;
    },
    async deleteContact(id) {
      const rows = await sql`DELETE FROM contacts WHERE id = ${id} RETURNING id`;
      return rows.length > 0;
    },
  };
}

async function createSqliteDatabase() {
  if (process.env.NODE_ENV === "production") throw new Error("DATABASE_URL is required in production.");
  const { default: Database } = await import("better-sqlite3");
  const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
  const defaultPath = path.resolve(currentDirectory, "../../backend/portfolio.db");
  const databasePath = path.resolve(process.env.SQLITE_DATABASE_PATH || defaultPath);
  const db = new Database(databasePath);
  db.pragma("journal_mode = WAL");
  db.exec(schema
    .replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
    .replaceAll("TIMESTAMPTZ", "DATETIME"));
  return {
    type: "sqlite",
    async health() { db.prepare("SELECT 1").get(); },
    async createContact({ name, email, message }) {
      return Number(db.prepare("INSERT INTO contacts (name, email, message) VALUES (?, ?, ?)").run(name, email, message).lastInsertRowid);
    },
    async listContacts() { return db.prepare("SELECT * FROM contacts ORDER BY created_at DESC, id DESC").all(); },
    async markContactRead(id) { return db.prepare("UPDATE contacts SET read_at = COALESCE(read_at, CURRENT_TIMESTAMP) WHERE id = ?").run(id).changes > 0; },
    async deleteContact(id) { return db.prepare("DELETE FROM contacts WHERE id = ?").run(id).changes > 0; },
    async close() { db.close(); },
  };
}

export function getDatabase() {
  if (databaseOverride) return Promise.resolve(databaseOverride);
  if (!databasePromise) databasePromise = process.env.DATABASE_URL
    ? createPostgresDatabase(process.env.DATABASE_URL)
    : createSqliteDatabase();
  return databasePromise;
}

export function setDatabaseForTests(database) {
  databaseOverride = database;
  databasePromise = undefined;
}

export async function resetDatabaseForTests() {
  if (databasePromise) {
    const database = await databasePromise;
    await database.close?.();
  }
  databasePromise = undefined;
  databaseOverride = undefined;
}
